// ADR index generator + SDD §15 status sync (feedback IMP-4). Front-matter is
// the single source of truth for ADR status/title.
const fs = require('node:fs');
const path = require('node:path');
const { readFrontMatter } = require('./consistency-gate.js');

const I_START = '<!-- ADR-INDEX:START — generated by adr-index.js, do not edit between markers -->';
const I_END = '<!-- ADR-INDEX:END -->';

function loadAdrFm(dir) {
  const adrDir = path.join(dir, 'adr');
  const out = [];
  if (!fs.existsSync(adrDir)) return out;
  for (const f of fs.readdirSync(adrDir).sort()) {
    if (!f.endsWith('.md') || f === 'index.md') continue;
    const fm = readFrontMatter(fs.readFileSync(path.join(adrDir, f), 'utf8'));
    if (fm.id) out.push(fm);
  }
  return out;
}

function renderIndex(adrs) {
  const rows = adrs.map(a =>
    `| ${a.id} | ${a.title || '—'} | ${a.status || '—'} | ${a.date || '—'} |`).join('\n');
  return `${I_START}\n\n# ADR Index\n\n| ADR | Title | Status | Date |\n| --- | --- | --- | --- |\n${rows}\n\n${I_END}\n`;
}

function writeIndex(dir) {
  const adrs = loadAdrFm(dir);
  fs.writeFileSync(path.join(dir, 'adr', 'index.md'), renderIndex(adrs));
  return adrs;
}

module.exports = { loadAdrFm, renderIndex, writeIndex, I_START, I_END };

if (require.main === module) {
  const dir = path.resolve(process.argv[2] || '.product');
  const adrs = writeIndex(dir);
  console.log(`adr-index: wrote ${adrs.length} ADR(s) to ${path.join(dir, 'adr', 'index.md')}`);
}
